#!/usr/bin/env Rscript

###### 
# This script will generate a sample file for demultiplexing for Gorka's run at the core
# input: 	sample identifying information with barcodes
#			example sample sheet for demultiplexing
# output: 	sample sheet for demultiplexing for Gorka's stuff
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
output.path <- c("../files_from_Gorka/")	# path for all output to go into
#############################


sample_sheet <- read.table(file=paste(output.path, "EMILY HCS Sample Sheet.csv", sep=""), sep=",", header=TRUE)

data <- read.table(file=paste(output.path, "Pinto_SampleID Barcodes_CRS TEVA MIST.txt", sep=""), sep="\t", header=TRUE)

FCID <- rep("AH9D56ADXX", dim(data)[1])

Lane <- c()
for (i in 1:dim(data)[1]) {
	if (data$pool[i] == "JP1") {
		Lane <- c(Lane, 1)
	} else {
		Lane <- c(Lane, 2)
	}
}

SampleID <- as.character(data$sampleID)

SampleRef <- rep("16SrRNA", dim(data)[1])

Index <- as.character(data$index)

Descriptor <- rep("NA", dim(data)[1])

Recipe <- rep("NA", dim(data)[1])

Operator <- rep("TK", dim(data)[1])

new.sheet <- cbind(FCID, Lane, SampleID, SampleRef, Index, Descriptor, Recipe, Operator)
write.table(new.sheet, paste(output.path, "gorka_sample_sheet_MIST_CRS_TEVA_",today,"ERD.csv", sep=""), sep=",", row.names=FALSE, quote=FALSE)



