#!/usr/bin/env Rscript

###### 
# This script will generate a sample file for demultiplexing for Gorka's run at the core
# using QIIME
# input: 	sample identifying information with barcodes
#			example sample sheet for demultiplexing
# output: 	sample sheet for demultiplexing for Gorka's stuff
######

###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()							# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
output.path <- c("../files_from_Gorka/")	# path for all output to go into
#############################


##### Load library
library("Biostrings")



data <- read.table(file=paste(output.path, "Pinto_SampleID Barcodes_CRS TEVA MIST.txt", sep=""), sep="\t", header=TRUE, stringsAsFactors=FALSE)


##### Find the reverse complement of the index sequences:
for (i in 1:dim(data)[1]) {
	data$index[i] <- as.character(reverseComplement(DNAString(as.character(data$index[i]))))
}


##### Do JP1 first:
SampleID <- gsub("_", "", as.character(data$sampleID[which(data$pool == "JP1")]))
BarcodeSequence <- as.character(data$index[which(data$pool == "JP1")])
LinkerPrimerSequence <- rep("NA", length(SampleID))
Description <- as.character(data$project[which(data$pool == "JP1")])

mapping <- cbind(SampleID, BarcodeSequence, LinkerPrimerSequence, Description)
colnames(mapping)[1] <- paste("#", colnames(mapping)[1], sep="")
#write.table(mapping, paste(output.path, "JP1_mapping_file_for_QIIME_",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)
write.table(mapping[,c(1:2)], paste(output.path, "JP1_barcodes_reverse_complement_",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)

##### And JP2:
SampleID <- gsub("_", "", as.character(data$sampleID[which(data$pool == "JP2")]))
BarcodeSequence <- as.character(data$index[which(data$pool == "JP2")])
LinkerPrimerSequence <- rep("NA", length(SampleID))
Description <- as.character(data$project[which(data$pool == "JP2")])

mapping <- cbind(SampleID, BarcodeSequence, LinkerPrimerSequence, Description)
colnames(mapping)[1] <- paste("#", colnames(mapping)[1], sep="")
#write.table(mapping, paste(output.path, "JP2_mapping_file_for_QIIME_",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)
write.table(mapping[,c(1:2)], paste(output.path, "JP2_barcodes_reverse_complement_",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)


print("DONE!")
