#!/usr/bin/env Rscript

###### 
# This script will output a table with the number of sequences generated per sample 
# for Gorka's data
# input: 	file with lines in each fastq file
# output: 	table with reads sequenced per sample
#			figure with the number of reads sequenced per sample
######


###### PARAMETERS ##########
# Set the parameters:
today <- Sys.Date()											# Set the date that will go on the end of the files generated by this script
today <- format(today, format="%m%d%y")
#############################


lines <- read.table(file="/Users/erdavenport/clusterhome/gorka/data/summaries/fastq_lines_for_each_sample_060614ERD.txt", sep=" ", header=FALSE, stringsAsFactors=FALSE)

reads <- lines
reads$V1 <- reads$V1/4

sorted <- lines[order(reads$V1),]

colme <- function(x) {
	if (grepl("MI", x)) {
		return("blue")
	} else if (grepl("TEV", x)) {
		return("red") 
	} else if (grepl("CRS", x)) {
		return("pink")
	}
}

# Save table:
write.table(sorted, paste("/Users/erdavenport/Dropbox/Lab/Gorka/results/table.reads.sequenced.per.sample.",today,"ERD.txt", sep=""), sep="\t", row.names=FALSE, quote=FALSE)

pdf(paste("/Users/erdavenport/Dropbox/Lab/Gorka/results/barplot.reads.sequenced.per.sample.",today,"ERD.pdf", sep=""), width=10, height=5)
par(mfrow=c(1,2))

# regular scale:
barplot(sorted$V1, col=sapply(sorted$V2, colme), main="Reads sequenced per sample", ylab="reads", xlab="sample")
legend("topleft", fill=sapply(c("MI", "TEV", "CRS"), colme), legend=c("MI", "TEV", "CRS"), bty="n")
abline(h=median(sorted$V1[grepl("MI", sorted$V2)]), col=sapply("MI", colme))
abline(h=median(sorted$V1[grepl("TEV", sorted$V2)]), col=sapply("TEV", colme))
abline(h=median(sorted$V1[grepl("CRS", sorted$V2)]), col=sapply("CRS", colme))

# log scale:
barplot(log10(sorted$V1), col=sapply(sorted$V2, colme), main="Reads sequenced per sample", ylab="log10(reads)", xlab="sample")
abline(h=log10(median(sorted$V1[grepl("MI", sorted$V2)])), col=sapply("MI", colme))
abline(h=log10(median(sorted$V1[grepl("TEV", sorted$V2)])), col=sapply("TEV", colme))
abline(h=log10(median(sorted$V1[grepl("CRS", sorted$V2)])), col=sapply("CRS", colme))

dev.off()

print("DONE!")

